### ISSUE TITLE
Image d'entête: inverser le slogan avec le nom de notre regroupement

### ISSUE THREAD

**Issue by accq** [accq/site-web-accq#1]
Il s'agit d'une suggestion reçu par un membre

**Comment by accq** [comment]
L'image d'entête sera retravaillée par un infographiste s'impliquant dans l'Assemblée constituante citoyenne du Québec.

**Comment by flamontagne** [comment]
Nous n'avons pas eu de nouvelles à ce sujet depuis un bon bout de temps. Fermeture du billet.
