### ISSUE TITLE
Mettre le nouveau nom de l'ACCQ partout

### ISSUE THREAD

**Issue by flamontagne** [accq/site-web-accq#28]
Partout sur le site, changer:

**Assemblée constituante citoyenne du Québec**

Pour:

**Alliance pour une constituante citoyenne du Québec**

**Comment by daniellemorin** [comment]
On attend qu'un publipostage ait été envoyé à tous les signataires par Éric avant! OK ? Je te ferai signe François!!!

**Comment by flamontagne** [comment]
Oui pas de problème. J'attendrai ton signal!

**Comment by daniellemorin** [comment]
Je t'avais envoyé le courriel suivant samedi dernier.... J'essaierai dorénavant de penser à t'écrire ici!! :-)
____________________________________________________
Alors, ça y est, François! C'est l'temps!

Tu peux procéder au changement de nom partout sur le site Web de l'ACCQ pour ALLIANCE POUR UNE CONSTITUANTE CITOYENNE DU QUÉBEC!!!

Même chose pour la page Facebook nationale. Quant aux ACRQ, pour le moment, on pourrait remplacer "Assemblée constituante régionale québécoise" par "Alliance constituante régionale québécoise"!

Pour les pages Facebook des ACRQ, je pense que c'est seulement la photo de couverture qui doit être changée. Si ça nécessite un infographe, dis-le moi et je contacterai Mathieu Bonnier. Il pourra le faire, je crois.

Par le fait même, sur la page d'accueil du site Internet, tu pourrais  changer "Constituantes et Constituant" par "Citoyens et Citoyennes" . Ça doit faire 1 an, qu'Alain Bergeron le demande et c'est bien vrai que nous ne sommes par encore des Constituants.


Et aussi changer la page "nous joindre" pour ceci 


"À la suite de la 4e rencontre nationale qui s’est tenue à Trois-Rivières en mai 2016, il a été convenu de mettre sur pied huit comités dont les responsables auront pour rôle de coordonner les activités de l’ACCQ. En date du 24 novembre 2016, voici les responsables choisis :
 
 
Comité Communication               Jean-Claude Gauthier, ACRQ 13 - Laval
Comité Éducation citoyenne       Philippe Malric,  ACRQ 06 - Montréal
Comité Éthique                           Marie-Luce Fortier, ACRQ 03 – Capitale-Nationale
Comité Financement                   Éric Groleau, ACRQ 04 - Mauricie
Comité Multimédia (TI)                Marc-André Robillard, ACRQ 14 – Lanaudière
Comité Secrétariat-registrariat      Danielle Morin, ACRQ 05 - Estrie"

Il faudrait aussi, dans la page Organigramme, corriger les noms des comités nationaux pour les noms indiqués ci-dessus. Le comité Mobilisation conserve le même nom mais il faut ajouter le comité Événements et y mettre cette brève description : 


"Le comité Événements s'occupe principalement d'organiser les rencontres nationales mais aussi tout autre événement majeur de mobilisation. Il doit travailler en collaboration avec les autres comités pour planifier les rencontres nationales de façon à tenir compte des travaux réalisés par ceux-ci."


Il faudrait donc, puisque nous avons maintenant huit comités, ajouter la lettre "H" dans les images concernées.


Merci à toi!


Danielle

**Comment by flamontagne** [comment]
- Le nom a été remplacé partout sur le site. **Il reste cependant l'image d'entête à modifier.** Je vais tenter de retrouver l'image en vectoriel afin de changer le texte.

- Citoyennes et Citoyens sur la page d'accueil, c'est fait.

- La page "Nous joindre" a été mise à jour

- L'organigramme a été mis à jour. Par contre, il faut que l'infographe modifie l'image afin d'ajouter le 8ieme comité (lettre H).

**Comment by daniellemorin** [comment]
Quelle bonne nouvelle, François!!! Merci beaucoup. L'image "en vectoriel" ça veut dire quoi ? L'Image sans texte. Parce que probablement que j'ai l'image vierge.

Pour l'organigramme, je vais contacter Mathieu Bonnier.

[😊]

________________________________
De : François Lamontagne <notifications@github.com>
Envoyé : 23 décembre 2016 14:15
À : accq/site-web-accq
Cc : daniellemorin; Manual
Objet : Re: [accq/site-web-accq] Mettre le nouveau nom de l'ACCQ partout (#28)


  *   Le nom a été remplacé partout sur le site. Il reste cependant l'image d'entête à modifier. Je vais tenter de retrouver l'image en vectoriel afin de changer le texte.

  *   Citoyennes et Citoyens sur la page d'accueil, c'est fait.

  *   La page "Nous joindre" a été mise à jour

  *   L'organigramme a été mis à jour. Par contre, il faut que l'infographe modifie l'image afin d'ajouter le 8ieme comité (lettre H).

**Comment by flamontagne** [comment]
En fait, n'étant pas infographiste, je ne suis pas tout à fait certain d'utiliser le bon terme (vectoriel) :)

Ce qu'il faut retrouver c'est l'image originale avec les "calques" qui nous permettra de modifier le texte sur l'image.

**Comment by daniellemorin** [comment]
Je t'envoie l'image déjà modifiée par Mathieu.

Ça ta va ?


![constituons_qc01-alliance](https://cloud.githubusercontent.com/assets/23343212/21472297/a2bdfe16-caa0-11e6-96a2-6a38ab52727e.jpg)

**Comment by flamontagne** [comment]
La nouvelle image est en ligne! Elle est un peu plus haute que l'ancienne version mais le résultat est très bien quand même. 

Je laisse le ticket ouvert puisqu'il reste encore des images à changer.

**Comment by flamontagne** [comment]
![organigramme1_01](https://cloud.githubusercontent.com/assets/39555/22267193/e3c380da-e250-11e6-9f55-4e54485589a1.png)

![accq_v2](https://cloud.githubusercontent.com/assets/39555/22267213/fbc2199e-e250-11e6-966c-7fc7356b99a4.jpg)

**Comment by flamontagne** [comment]
Concernant les nouveaux logos (en rouge), est-ce qu'on doit les utiliser ou bien ce n'est pas encore officielle?

**Comment by daniellemorin** [comment]
Salut François!


Ces images sont des suggestions seulement. Elles ont été préparées par Mathieu Bonnier. Alors, faudrait voir avec Alain, Marc-André et Philippe si elles conviennent et si on peut revamper le site Internet avec celles-ci. En tout cas, ces mon opinion... [😊]


Danielle


________________________________
De : François Lamontagne <notifications@github.com>
Envoyé : 24 janvier 2017 16:45
À : accq/site-web-accq
Cc : daniellemorin; Manual
Objet : Re: [accq/site-web-accq] Mettre le nouveau nom de l'ACCQ partout (#28)


Concernant les nouveaux logos (en rouge), est-ce qu'on doit les utiliser ou bien ce n'est pas encore officielle?
