### ISSUE TITLE
Ajouter une page pour Mumble

### ISSUE THREAD

**Issue by Marc-AndreR** [accq/site-web-accq#30]
Il faut créé une page avec de lien pour de l'aide a l'installation, connexion, réglage et avec les codes accès a notre salle de discision.

 pour les zone de A a F
[Contenu_revisé.docx](https://github.com/accq/site-web-accq/files/700682/Contenu_revise.docx)

![onglet mumble](https://cloud.githubusercontent.com/assets/25062020/21859530/ea6cae26-d7fa-11e6-92cd-a5078f190532.png)

![download](https://cloud.githubusercontent.com/assets/25062020/21860117/327ce878-d7fd-11e6-9745-0903fd3f47a7.png)

**Comment by flamontagne** [comment]
Excellent, merci pour les infos. J'essaie de m'en occuper cette semaine (Je vais probablement commencer aujourd'hui)

**Comment by flamontagne** [comment]
Je viens de mettre en ligne la page Mumble. Merci de valider et me dire s'il y a des corrections à apporter!

Alain Bergeron m'a demandé d'ajouter sur cette page une section pour joindre les discussion des "Cercles de parole pour une Chambre citoyenne du Québec". Je crois que Danielle est au courant.

Je n'ai pas encore eu le temps d'ajouter cette section. De toute façon je crois qu'il me manque des informations.

**Comment by Marc-AndreR** [comment]
Personne na decider de rajouter une section cercle de parole citoyenne... c'est alain en son nom pour son projet qui ta demande ca.
 on ne rajoute pas ca pour l'instant

**Comment by Marc-AndreR** [comment]
Voici le code a copier colle dans la section" F"
<script type="text/javascript" src="https://view.light-speed.com/mumble.php?url=https%3A//api.mumble.com/mumble/cvp.php%3Ftoken%3DLSG-85-F8F57DEB&c=04418f&r=7&h=600&w=225&css=https%3A//view.light-speed.com/styles/mumble-minimal.css"></script>

**Comment by flamontagne** [comment]
C'est en ligne
