### ISSUE TITLE
Mumble dans le site Internet

### ISSUE THREAD

**Issue by daniellemorin** [accq/site-web-accq#31]
Salut!

Je crois qu'il serait bon de renommer l'onglet "Mumble" du site Internet pour Discutoire, ce qui serait plus attirant.

Quelques fautes détectées dans la page "Mumble" : 
- dans la 1e phrase - enlever le "s" à "outils";
- à deux endroits, "votre pseudo (doit permetre de vous identifier)", écrire "permettre" avec deux "t".

Merci!
Danielle

**Comment by Marc-AndreR** [comment]
Svp corriger dès que possible les fautes suivantes dans le site, section discutoire : "Nous mettons à votre disposition un OUTIL libre et gratuit..."

Merci!

**Comment by leluthierceleste** [comment]
Beau travail les amis, c'est bien de corriger nos fautes de Français, on a du boulot à faire très important !
Merci!

**Comment by flamontagne** [comment]
C'est fait, 2 mois plus tard dans les maritimes... désolé pour le délai!
